#!/bin/sh

. ./env

./checkstop
RESULT=$?
if [ $RESULT -eq 1 ]; then
    exit 0
elif [ $RESULT -gt 1 ]; then
    exit 1
fi

docker run -d -it \
-e TZ=Australia/Hobart \
--name ${NAME} \
-h ${NAME} \
-p 223:22 \
-v /var/run/docker.sock:/var/run/docker.sock \
-v ${NAME}-home:/home:rw \
${TAG} || exit 4

